import { TestPlan } from '@/types/precisionTest';

const testPlans: TestPlan[] = [
    {
        id: '1',
        name: '用户服务V1.2.0测试计划',
        status: 'completed',
        planType: 'functional',
        environment: '生产环境',
        projectName: 'AegisOne-UserService',
        branch: 'release/v1.2.0',
        tester: '张三',
        date: '2025-11-20 14:30',
        taskId: 'jacoco-task-001',
        caseCount: 45,
        passedCount: 42,
        failedCount: 3,
        codeCoverage: 85,
        packageCoverage: [
            {
                packageName: 'com.aegisone.user',
                lineCoverage: 85,
                lineCovered: 340,
                lineTotal: 400,
                branchCoverage: 78,
                branchCovered: 78,
                branchTotal: 100,
                methodCoverage: 90,
                classCoverage: 88,
            },
            {
                packageName: 'com.aegisone.order',
                lineCoverage: 72,
                lineCovered: 288,
                lineTotal: 400,
                branchCoverage: 65,
                branchCovered: 65,
                branchTotal: 100,
                methodCoverage: 80,
                classCoverage: 75,
                classes: [
                    {
                        className: 'OrderController.java',
                        lineCoverage: 68,
                        lineCovered: 102,
                        lineTotal: 150,
                        branchCoverage: 60,
                        branchCovered: 24,
                        branchTotal: 40,
                        methodCoverage: 75,
                        classCoverage: 70,
                    },
                    {
                        className: 'OrderService.java',
                        lineCoverage: 75,
                        lineCovered: 186,
                        lineTotal: 248,
                        branchCoverage: 70,
                        branchCovered: 42,
                        branchTotal: 60,
                        methodCoverage: 85,
                        classCoverage: 80,
                    },
                ],
            },
            {
                packageName: 'com.aegisone.common',
                lineCoverage: 95,
                lineCovered: 285,
                lineTotal: 300,
                branchCoverage: 92,
                branchCovered: 92,
                branchTotal: 100,
                methodCoverage: 98,
                classCoverage: 100,
            },
        ],
        coverageReports: [
            {
                id: '1',
                fileName: 'UserController.java',
                filePath: 'com/aegisone/user/UserController.java',
                lineCoverage: 85.5,
                branchCoverage: 78.2,
                methodCoverage: 89,
                classCoverage: 88,
                totalLines: 66,
                coveredLines: 56,
                uncoveredLines: 10,
                lastUpdate: '2025-11-20 14:30:00',
                status: 'success',
            },
            {
                id: '2',
                fileName: 'UserService.java',
                filePath: 'com/aegisone/user/UserService.java',
                lineCoverage: 92.3,
                branchCoverage: 85.7,
                methodCoverage: 95,
                classCoverage: 90,
                totalLines: 120,
                coveredLines: 111,
                uncoveredLines: 9,
                lastUpdate: '2025-11-20 14:25:00',
                status: 'success',
            },
        ],
    },
    {
        id: '2',
        name: '订单服务核心功能测试',
        status: 'running',
        planType: 'functional',
        environment: '测试环境',
        projectName: 'AegisOne-OrderService',
        branch: 'main',
        tester: '李四',
        date: '2025-11-21 09:15',
        taskId: 'jacoco-task-002',
        caseCount: 38,
        passedCount: 35,
        failedCount: 3,
        codeCoverage: 72,
        coverageReports: [
            {
                id: '3',
                fileName: 'OrderController.java',
                filePath: 'com/aegisone/order/OrderController.java',
                lineCoverage: 72.5,
                branchCoverage: 65.2,
                methodCoverage: 80,
                classCoverage: 75,
                totalLines: 88,
                coveredLines: 64,
                uncoveredLines: 24,
                lastUpdate: '2025-11-21 09:15:00',
                status: 'warning',
            },
        ],
    },
    {
        id: '3',
        name: '支付模块集成测试',
        status: 'failed',
        planType: 'functional',
        environment: '开发环境',
        projectName: 'AegisOne-PaymentService',
        branch: 'feature/alipay',
        tester: '王五',
        date: '2025-11-22 16:45',
        taskId: 'jacoco-task-003',
        caseCount: 52,
        passedCount: 40,
        failedCount: 12,
        codeCoverage: 58,
        coverageReports: [
            {
                id: '4',
                fileName: 'PaymentController.java',
                filePath: 'com/aegisone/payment/PaymentController.java',
                lineCoverage: 58.5,
                branchCoverage: 48.2,
                methodCoverage: 65,
                classCoverage: 60,
                totalLines: 95,
                coveredLines: 55,
                uncoveredLines: 40,
                lastUpdate: '2025-11-22 16:45:00',
                status: 'error',
            },
        ],
    },
    {
        id: '4',
        name: '用户服务V1.3.0测试计划',
        status: 'running',
        planType: 'unit',
        environment: '测试环境',
        projectName: 'AegisOne-UserService',
        branch: 'develop',
        tester: '张三',
        date: '2025-11-23 10:20',
        taskId: 'jacoco-task-004',
        caseCount: 48,
        passedCount: 45,
        failedCount: 1,
        codeCoverage: 78,
        coverageReports: [
            {
                id: '5',
                fileName: 'UserController.java',
                filePath: 'com/aegisone/user/UserController.java',
                lineCoverage: 78.5,
                branchCoverage: 72.2,
                methodCoverage: 82,
                classCoverage: 80,
                totalLines: 66,
                coveredLines: 52,
                uncoveredLines: 14,
                lastUpdate: '2025-11-23 10:20:00',
                status: 'warning',
            },
        ],
    },
    {
        id: '5',
        name: '通用工具类单元测试',
        status: 'completed',
        planType: 'unit',
        environment: '开发环境',
        projectName: 'AegisOne-Common',
        branch: 'main',
        tester: '赵六',
        date: '2025-11-24 11:00',
        taskId: 'jacoco-task-005',
        caseCount: 32,
        passedCount: 32,
        failedCount: 0,
        codeCoverage: 95,
        coverageReports: [
            {
                id: '6',
                fileName: 'StringUtils.java',
                filePath: 'com/aegisone/common/StringUtils.java',
                lineCoverage: 95.5,
                branchCoverage: 92.2,
                methodCoverage: 98,
                classCoverage: 100,
                totalLines: 45,
                coveredLines: 43,
                uncoveredLines: 2,
                lastUpdate: '2025-11-24 11:00:00',
                status: 'success',
            },
        ],
    },
];

export const getTestPlans = (): Promise<TestPlan[]> => {
    return Promise.resolve(testPlans);
};
